### ISSUE TITLE
Process is terminated due to StackOverflowException

### ISSUE THREAD

**Issue by neothor** [nightroman/SplitPipeline#11]
I am using your project to execute processes in parallel. Only I get an exception. -Verbose gave me the following information.

```
Split-Pipeline :
At C:\.S\tasty-3\.build\modules\Testing.psm1:54 char:17
+     $projects | Split-Pipeline -Verbose -Variable data -Count $settings.tools.nu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [Split-Pipeline], RemoteException
    + FullyQualifiedErrorId : NativeCommandError,SplitPipeline.SplitPipelineCommand

Split-Pipeline : Process is terminated due to StackOverflowException.
At C:\.S\tasty-3\.build\modules\Testing.psm1:54 char:17
+     $projects | Split-Pipeline -Verbose -Variable data -Count $settings.tools.nu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Split-Pipeline], RemoteException
    + FullyQualifiedErrorId : NativeCommandErrorMessage,SplitPipeline.SplitPipelineCommand

VERBOSE: Split-Pipeline:
Item count = 64
Part count = 5
Pipe count = 5
Wait count = 5
Max queue  = 64
Total time = 00:05:21.0455479
Items /sec = 0,199348660707592
```

What is unclear to me is which process failed and if the exception is within SplitPipeline, the scriptblock or the program that is called within the scriptblock.

**Comment by nightroman** [comment]
Some more information would be useful. If you cannot provide the code or a simplified test case then try to describe it. Does your code call something recursively, does it call something that calls something recursively, etc.? What it is the exact command you use? I can see only this piece:

    Split-Pipeline -Verbose -Variable data -Count $settings.tools.nu ...

Also, after the failure in the same session try to examine the full content of `$Error`. Sometimes it gets more errors in addition to the last and more clues.

**Comment by nightroman** [comment]
(A silly question but I better ask) Your scriptblock works in a normal pipeline (without Split-Pipeline) and fails with Split-Pipeline. Correct?

**Comment by neothor** [comment]
The following code is used to kick it off. There is still some code smell ;)
```
$projects | Split-Pipeline -Verbose -Variable data -Count $settings.tools.nunit.numberOfJobs { 
        process {
            $result = New-Object PSObject -Property @{
                "Name" = $_.Name;
                "Path" = $_.Path;
                "Elapsed" = $null;
                "Output" = $null;
                "Successfull" = $false;
            }

            try {
                $done = $data.Done
                $precent = [System.Math]::Round((100*$done/$data.Count), 0)

                $nunit = $_.NUnit
                $project = $_.Path
                $xml = $_.Xml

                Write-Host "[$($precent)%][Starting] $($result.Name)" -ForegroundColor Gray

                $stopWatch = [System.Diagnostics.Stopwatch]::StartNew()
                $result.Output = & $nunit $project /nologo /nodots /process=multiple /xml=$xml
                $result.Elapsed = $stopWatch.Elapsed
                
                $done = ++$data.Done
                $precent = [System.Math]::Round((100*$done/$data.Count), 0)
                
                if ($global:LASTEXITCODE -gt 0) {
                    Write-Host "[$($precent)%][Failed][$($result.Elapsed)] $($result.Name)" -ForegroundColor Red
                } else {
                    $result.Successfull = $true
                    Write-Host "[$($precent)%][Completed][$($result.Elapsed)] $($result.Name)"
                }

                
            }
            catch [Exception] {
                Write-Host "[Exception] $($result.Name) $_" -ForegroundColor Red
            }

            $data.Results += $result
        }
    }
```

But it seems that the problem lies within the nunit project itself. What I find interesting is that is isn't caught by my catch.

**Comment by nightroman** [comment]
> But it seems that the problem lies within the nunit project itself.

That is what I think so far. Your script do not use recursion and even it were then the error would be *"Split-Pipeline : The script failed due to call depth overflow."*

> What I find interesting is that is isn't caught by my catch.

This is an interesting bit. `StackOverflowException` is a fatal error, an application just crashes. But what is `$nunit` in you case? It is probably an external application (exe, cmd, etc.). In this case in your script there is no exception from it at all. You should check for `$LastExitCode` after calling `$nunit`. If it is not 0 then normally it means an error. You do check it but slightly differently: `$global:LASTEXITCODE`. Why global?

**Comment by nightroman** [comment]
It looks like there is nothing wrong in `Split-Pipeline` and I am going to close the issue.

I can see potential problems in your script. Let me know if you want me to explain.

**Comment by neothor** [comment]
I agree Split-Pipeline seems to work find. The script still needs to be cleaned up but I would like to know what you see as potential problems.

**Comment by nightroman** [comment]
[Test-ProgressTotal.ps1]: https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal.ps1

The main problem I see is simultaneous access to the shared data (`$data`) from
parallel pipelines.  It would be fine perhaps for reading but you do
`++$data.Done` and `$data.Results += $result`. The first one is not so
important if you use it just for showing progress. But the second is important,
it is a potential mistake, you may not find all results there.

How to deal with this. The best way is to avoid use of shared data at all. For
example, for results instead of `$data.Results += $result` just output results
as `$result` and process them further:

```powershell
$projects | Split-Pipeline -Verbose -Variable data -Count $settings.tools.nunit.numberOfJobs {
    process {
        $result = New-Object PSObject ...
        ...
        $result
    }
} | .{process{
    $_ # the current result
}}
```

or simply collect all results from pipelines and process later:

```powershell
$results = $projects | Split-Pipeline ...
```

But if you still want to use shared data then take a look at the issue #4 and
at the script [Test-ProgressTotal.ps1], it shows how to use `Monitor` for safe
access to shared data from pipelines.

Feel free to ask more questions, no problem. Or close the issue if we are done.

**Comment by neothor** [comment]
Thank you for your feedback and I will make the appropriate changes. I will close the issue now since I think I have enough resources. Too bad github dropped the private message support.
