### ISSUE TITLE
Possible Switch block and Try-Catch block scoping issue inside Split-Pipeline process block

### ISSUE THREAD

**Issue by shemsargent-rvtd** [nightroman/SplitPipeline#18]
When I place a Switch block or Try-Catch block in a Split-Pipeline process block, the variables in the process block are not visible inside them. Any thoughts on a workaround, or is this a hard limitation of this method?

**Comment by nightroman** [comment]
`switch` and `try/catch` should not have these problems, the should see variables in the process block.

Example: `$myItem` is defined in `process` and it is visible in `try` and `catch`

```powershell
1..9 | Split-Pipeline {
    process {
        $myItem = $_
        try {
            if ($_ % 2) {
                throw "oops"
            }
            "Done: $_ ($myItem)"
        }
        catch {
            "Failed: $myItem ; Error: $_"
        }
    }
}
```

Are you perhaps talking about the pipeline variable `$_`? Then it is a known
feature of `switch` and `catch` because they use their own variable `$_` which
hides the existing `$_`.

If yes, then this is not really an issue of `Split-Pipeline`. The workaround is
shown above, use some `$myItem` in order to keep the current item for `switch`
and `catch` blocks.

If no, then I need an example of the problem.
