### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by dklingman** [nightroman/SplitPipeline#26]
I'd like to make use of the End script block portion, but I'm not sure how to implement this?  I have my begin and process blocks working but not the end.

**Comment by nightroman** [comment]
No problem. Please show the example of what you have so far. But without details I would say:

```powershell
... | Split-Pipeline {
    begin {...}
    process {...}
    end {...}
}
```

**Comment by dklingman** [comment]
The following is something was just playing around with to get the End script to work.  My real code does not have the End script block in it just yet
`
Import-Module SplitPipeline
[System.IO.DirectoryInfo]$di = [System.IO.DirectoryInfo]::new("C:\Projects\Deployment\DeploymentFiles\SSRSReports")

$items = $di.GetFiles("*.rdl")
$lastId = [ref]0
$data = @{
    Count = $items.Count
    Done = 0
}

$sw = [System.Diagnostics.Stopwatch]::StartNew()
$items | Split-Pipeline -Count 3 -Variable data, lastId { process {

    
    [System.Threading.Monitor]::Enter($data)
    try{
        $info = [System.Collections.Generic.List[string]]::new()

        $files = @($input)
        foreach($sz in $files) {
            #SSRS Upload will occur here.
            ++$data.Done

            #test to try to get output information for end block script
            $info.Add($sz)
	    }
        return $info
    }
    finally{
        [System.Threading.Monitor]::Exit($data)
    }
}} -Begin {
	$id = ++$lastId.Value
} -End {
    Write-Host $_
} | Out-Null

if ($data.Done -ne $items.Count) { throw 'Processed and input item counts must be equal.' }

$sw.stop()
Write-Host ([System.Diagnostics.Stopwatch]$sw).Elapsed

`

**Comment by nightroman** [comment]
I see, you are talking about the pipeline `-Begin` and `-End`. I think `$_` is not a thing in your `-End { Write-Host $_ }`. What do you think `$_` is there? What are you trying to write?

**Comment by nightroman** [comment]
There are several issues. Please find them corrected in the below script (with simplified data).

(1) You probably want to write `$id` in your `-End {}`.

(2) You decided to process data by whole batches `$input` instead of the usual
approach `{process{ $_ }}`. It's fine but then you should use `{end{ $input }}`.
I have also removed `| Out-Null` so that we can see the output, for test sake.

(3) Using locks (`[System.Threading.Monitor]` in your case) for changing shared
data is the right thing to do. But you are using them "incorrectly", you lock
pipelines for the whole batches of data, effectively killing parallel processing.
You should use `Enter` and `Exit` just around the piece of code changing `$data`.

(4) Optional. Instead of `[System.Threading.Monitor]` with `try/finally` you may
use simpler `SplitPipeline` helper `$Pipeline.Lock({...})`.

As a result, the corrected script outputs ids 1, 2, 3 (order is not deterministic)
and the final check (`$data.Done` is equal to `$items.Count`) passes.

```powershell
Import-Module SplitPipeline

$items = 1..11 | .{process{ "Item $_" }}
$lastId = [ref]0
$data = @{
    Count = $items.Count
    Done = 0
}

$items | Split-Pipeline -Count 3 -Variable data, lastId {end{
    $info = [System.Collections.Generic.List[string]]::new()
    $files = @($input)
    foreach($sz in $files) {
        # actual work will occur here

        # increment common counter
        $Pipeline.Lock({++$data.Done})

        $info.Add($sz)
    }
    $info
}} -Begin {
    $id = ++$lastId.Value
} -End {
    Write-Host $id
}

if ($data.Done -ne $items.Count) { throw 'Processed and input item counts must be equal.' }
```

**Comment by nightroman** [comment]
It's up to you and it depends on your exact requirements.
For simple cases I would use the usual `{process{ $_ }}`.
The code is usually simpler.

```powershell
$items | Split-Pipeline -Count 3 -Variable data, lastId {process{
    # actual work will occur here
    $_

    # increment common counter
    $Pipeline.Lock({++$data.Done})
}} -Begin {
    $id = ++$lastId.Value
} -End {
    Write-Host $id
}
```
