### ISSUE TITLE
contributing - running tests

### ISSUE THREAD

**Issue by ghostsquad** [nightroman/SplitPipeline#7]
I'd like to contribute, but I'm unable to run your tests. `task : The term 'task' is not recognized as..`.

**Comment by nightroman** [comment]
Tests are invoked by [Invoke-Build]. I recommend to download the package (see
README) because it includes the generated XML help file for PowerShell help and
satellite utility scripts. You may find Invoke-Build useful for something else.

But you get get just the script [Invoke-Build.ps1], it is enough. Just put it
somewhere in the path. Examples of using it:

Invoke the test/task *SomeTest* in *Some.test.ps1*:

    PS> Invoke-Build SomeTest Some.test.ps1

Invoke all tests in *Some.test.ps1*:

    PS> Invoke-Build * Some.test.ps1

Invoke all `*.test.ps1` files in the current directory recursively:

    PS> Invoke-Build **

Or even better set the current location to the root project directory and invoke

    PS> Invoke-Build Test

This command invokes the task *Test* from *.build.ps1*. It runs tests with
PowerShell 2.0 and then with the current PowerShell.

[Invoke-Build]: https://github.com/nightroman/Invoke-Build
[Invoke-Build.ps1]: https://github.com/nightroman/Invoke-Build/blob/master/Invoke-Build.ps1

**Comment by ghostsquad** [comment]
there are some broken image links here:
https://github.com/nightroman/Invoke-Build/wiki/Show-Build-Graph

**Comment by nightroman** [comment]
Thank you, broken image links are fixed now.
